config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resource :home, only: :index

  resource :mail_list, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/mail_lists_controller.rb
# frozen_string_literal: true

class MailListsController < ApplicationController
  def create
    MailList.sign_up(mail_list_params)
    head 201
  end

  private

  def mail_list_params
    params.require(:mail_list).permit(:email, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.haml
%iframe{ src: '/mirrors.mp3', allow: 'autoplay', style: 'display: none', id: 'iframeAudio' }
= audio_tag('/mirrors.mp3', autoplay: true, loop: true, class: 'background-music')
.mute-icon
  .fas.fa-volume-up.fa-lg
.row.logo-container
  .offset-md-2.col-md-8.offset-1.col-10
    = image_tag('morale-logo.png', class: 'logo align-bottom')
.social-media
  = link_to 'https://www.facebook.com/moralebanduk', class: 'social-media-link', target: '_blank' do
    .fab.fa-facebook-square.social-media-logo.fa-2x
  = link_to 'https://twitter.com/MoraleBandUK', class: 'social-media-link', target: '_blank' do
    .fab.fa-twitter.social-media-logo.fa-2x
  = link_to 'https://www.instagram.com/moralebanduk', class: 'social-media-link', target: '_blank' do
    .fab.fa-instagram.social-media-logo.fa-2x
  = link_to 'https://www.youtube.com/watch?v=jlZ8BP15_E8', class: 'social-media-link', target: '_blank' do
    .fab.fa-youtube.social-media-logo.fa-2x
  = link_to 'https://itunes.apple.com/us/artist/morale/1386819245', class: 'social-media-link', target: '_blank' do
    .fab.fa-apple.social-media-logo.fa-2x
  = link_to 'https://open.spotify.com/artist/6GRMSo8aC09i25DVa8KVSO?si=cA-WRHYMRhOQ1kppPRyEDw', class: 'social-media-link', target: '_blank' do
    .fab.fa-spotify.social-media-logo.fa-2x

-# .mail-list
-#   %a.mail-modal{ href: '#', data: { toggle: 'modal', target: '#mail-list-modal' } }
-#     %i.far.fa-envelope-open.fa.2x.social-media-logo
-#     JOIN OUR MAIL LIST

-# #mail-list-modal.modal.fade{role: "dialog", tabindex: "-1"}
-#   .modal-dialog.modal-dialog-centered{role: "document"}
-#     .modal-content
-#       .modal-header
-#         %h5.modal-title Join Our Mail List
-#         %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
-#           %span{"aria-hidden" => "true"} ×
-#       = form_for :mail_list, url: mail_list_path, remote: true, html: { id: 'mail-list-form', autocomplete: 'off' } do |f|
-#         .modal-body
-#           .form-group
-#             = f.label :email
-#             = f.text_field :email, id: 'mail-list-email-input', class: 'form-control'
-#             = f.label :first_name
-#             = f.text_field :first_name, id: 'mail-list-email-first-name', class: 'form-control'
-#             = f.label :last_name
-#             = f.text_field :last_name, id: 'mail-list-email-last-name', class: 'form-control'
-#         .modal-footer
-#           %button.btn.btn-sm.btn-secondary{"data-dismiss" => "modal", type: "button"} Close
-#           = f.submit 'Add to mail list', id: 'mail-list-submit', class: 'btn btn-sm btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport" }
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }
    %meta{ content: "New single 'Mirrors' out now!!", name: 'description' }
    %title 𝙈 𝙊 𝙍 𝞚 𝙇 𝙀
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'
  %body
    .container-fluid#overlay
      = yield